Repository merzlab/QUICK, pull requests merged in 2024-03, with the labels that each got.

#322 Fix for compile time error that occurs with intel compiler tool chain
  src/modules/include/eri.fh
Labels: bug

#332 Fix for issues 323 and 325
  src/basis.f90
  src/cuda/gpu_get2e_getxc_drivers.h
  src/cuda/gpu_get2e_grad_ffff.cuh
  src/modules/include/gradient.fh
  src/modules/quick_oei_module.f90
  tools/runtest
Labels: Bug fix

#335 F trap for cEW enabled QM/MM
  src/basis.f90
  src/modules/quick_exception_module.f90
Labels: enhancement

#339 Error trap for UHF/UDFT calculations with basis sets containing F functions and CUDA version
  src/basis.f90
  src/getMol.f90
  src/modules/quick_exception_module.f90
Labels: enhancement

#334 Fix for issue 333
  src/basis.f90
  src/modules/quick_basis_module.f90
  src/modules/quick_molden_module.f90
Labels: Bug fix

#346 Support for legacy atomics in cuda f gradient kernels
  src/cuda/gpu_common.h
  src/cuda/gpu_get2e_grad_ffff.cu
  src/cuda/gpu_get2e_grad_ffff.cuh
Labels: Code cleanup, Bug fix

#349 Fix for issue 337
  src/cuda/gpu.cu
Labels: Bug fix

#354 AWG Update runtest script for Amber
  test/Run.tests.amber
  tools/runtest
Labels: Code cleanup

#355 Update to CMakeListst.txt
  CMakeLists.txt
Labels: Bug fix
