Repository merzlab/QUICK, pull requests merged in 2025-03, with the labels that each got.

#406 All types of whitespace characters used for delineation are not correctly parsed in input files
  src/subs/findBlock.f90
  test/saved/grad_naip_meoh_libxc_pbeh_def2svp.out
  test/saved/grad_naip_meoh_libxc_pbeh_sto3g.out
  test/saved/grad_ncnaip_b3lyp_631gss.out
  test/saved/grad_ncnaip_b3lyp_sto3g.out
  test/saved/grad_rpsb_meoh_rhf_321g.out
  test/saved/grad_rpsb_meoh_rhf_sto3g.out
Labels: bug

#403 GitHub CI Workflow Enhancements Part 5
  .github/workflows/build_test_mpi.yml
  .github/workflows/build_test_serial.yml
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  src/CMakeLists.txt
  src/dlfind/dlf_util.f90
  src/dlfind/dlfind_main_driver.f90
  src/dnc/dnc_hfoperator.f90
  src/hessian.f90
  src/main.f90
  src/modules/Makefile
  src/modules/include/eri.fh
  src/modules/include/eri_grad.fh
  src/modules/include/gradient.fh
  src/modules/quick_api_module.f90
  src/modules/quick_eri_cshell_module.f90
  src/modules/quick_eri_grad_cshell_module.f90
  src/modules/quick_eri_grad_oshell_module.f90
  src/modules/quick_eri_oshell_module.f90
  src/modules/quick_grad_cshell_module.f90
  src/modules/quick_grad_oshell_module.f90
  src/modules/quick_lri_grad_module.f90
  src/modules/quick_method_module.f90
  src/modules/quick_optimizer_module.f90
  src/modules/quick_sad_guess_module.f90
  src/modules/quick_scf_operator_module.f90
  src/modules/quick_uscf_operator_module.f90
  src/obsolete/gradient.f90
  src/obsolete/optimize.f90
  src/obsolete/scf_operator.f90
  src/subs/pt2der.f90
  src/subs/sswder.f90
Labels: enhancement

#409 GitHub CI Workflow Enhancements Part 6
  .github/workflows/build_test_mpi.yml
  .github/workflows/build_test_serial.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/gpu/cuda/CMakeLists.txt
  src/gpu/cuda/mgpu.h
  src/gpu/hip/CMakeLists.txt
  src/lapack/CMakeLists.txt
  src/libxc/CMakeLists.txt
Labels: enhancement

#411 HIP and MPI+HIP Updates Part 2
  src/gpu/cuda/gpu.cu
  src/gpu/cuda/gpu.h
  src/gpu/cuda/mgpu.h
  src/gpu/hip/gpu.cu
  src/gpu/hip/gpu.h
  src/gpu/hip/mgpu.h
  src/libxc/CMakeLists.txt
  src/libxc/gpu_cleanup.cu
  src/libxc/gpu_upload.cu
  src/main.f90
  src/modules/quick_api_module.f90
Labels: Code cleanup, Bug fix
