Repository merzlab/QUICK, pull requests merged in 2025-02, with the labels that each got.

#394 GitHub CI Workflow Enhancements Part 4
  .github/workflows/build_test_mpi.yml
  .github/workflows/build_test_serial.yml
  configure
  src/dlfind/dlf_dimer.f90
  src/dlfind/dlf_formstep.f90
  src/dlfind/dlf_qts.f90
  src/dlfind/dlf_serial.f90
  src/dlfind/dlf_task.f90
  src/modules/quick_calculated_module.f90
Labels: enhancement

#398 AWG: Remove duplicate definition of DLFIND_MODULES_SOURCES
  src/CMakeLists.txt
Labels: Code cleanup

#402 Fix Setting Compilation Flags for GitHub CI Workflow Tests
  .github/workflows/build_test_mpi.yml
  .github/workflows/build_test_serial.yml
Labels: Bug fix
